### ISSUE TITLE
AirMapper on the App Store?

### ISSUE THREAD

**Issue by andris1** [mjdoiron/AirMapper#1]
Hi Matt,

I stumbled on your app while searching for an intuitive fog of war airplay app. It seems to fit the bill perfectly. Unfortunately, I'm not really a dev so I'm not quite sure how to take the source code and turn it into an app. Would you ever consider putting AirMapper up on the App Store? I would be very interested in buying it.

P.S. Sorry for posting this as an issue; the email form was returning an error.

**Comment by mjdoiron** [comment]
Hey Andris,
Im glad you liked it but I dont think I am going to put it up in the App
Store since its really not complete. I ran into a problem where there was a
major performance issue if you used a map that was high resolution. To be
honest the purpose of the project was to show off some skills on my resume
when I was looking for a new job, which is no longer an issue since I have
a job now. One of these days I might come back to it, but I basically need
an entirely new drawing strategy to get the performance needed.

Sorry, but thanks anyways. If you ever want to get into programming though
the code is free to use.

-Matt


On April 2, 2018 at 10:10:01 AM, Andris (notifications@github.com) wrote:

Hi Matt,

I stumbled on your app while searching for an intuitive fog of war airplay
app. It seems to fit the bill perfectly. Unfortunately, I'm not really a
dev so I'm not quite sure how to take the source code and turn it into an
app. Would you ever consider putting AirMapper up on the App Store? I would
be very interested in buying it.

P.S. Sorry for posting this as an issue; the email form was returning an
error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mjdoiron/AirMapper/issues/1>, or mute the thread

**Comment by andris1** [comment]
Ah, fair enough. I appreciate you getting back to me anyway. Glad the job situation worked out. :)
